export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/1.jpeg",
    username: "YALIM GÜRBÜZ",
  },
  {
    id: 2,
    profilePicture: "assets/person/2.jpeg",
    username: "yalım gürbüz1",
  },
  {
    id: 3,
    profilePicture: "assets/person/3.jpeg",
    username: "yalım gürbüz2",
  },
  {
    id: 4,
    profilePicture: "assets/person/4.jpeg",
    username: "yalım gürbüz3",
  },
  {
    id: 5,
    profilePicture: "assets/person/5.jpeg",
    username: "yalım gürbüz4",
  },
  {
    id: 6,
    profilePicture: "assets/person/6.jpeg",
    username: "yalım gürbüz5",
  },
  {
    id: 7,
    profilePicture: "assets/person/7.jpeg",
    username: "yalım gürbüz6",
  },
  {
    id: 8,
    profilePicture: "assets/person/8.jpeg",
    username: "yalım gürbüz7",
  },
  {
    id: 9,
    profilePicture: "assets/person/9.jpeg",
    username: "yalım gürbüz8",
  },
  {
    id: 10,
    profilePicture: "assets/person/10.jpeg",
    username: "yalım gürbüz9",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "AÇIKLAMA",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "AÇIKLAMA",

    photo: "assets/post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "AÇIKLAMA",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/4.jpeg",
    desc: "AÇIKLAMA",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    desc: "AÇIKLAMA",
    photo: "assets/post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    desc: "AÇIKLAMA",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "AÇIKLAMA",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    desc: "AÇIKLAMA",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "AÇIKLAMA",
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/post/10.jpeg",
    desc: "AÇIKLAMA",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
